version: '3.5'

services:
#  weareopensourceNode:
#    container_name: weareopensourceNode
#    image: weareopensource/node:latest
#    restart: always
#    ports:
#      - 3000:3000
#    volumes:
#      - weareopensourceNode:/data
#    networks:
#      - mongo
#    depends_on:
#      - mongo
#    environment:
#      - 'WAOS_NODE_db_uri=mongodb://mongo:27017/WaosNodeDev'
#      - 'WAOS_NODE_host=0.0.0.0'

  mongo:
    image: mongo:latest
    ports:
      - "27017:27017"
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: root
      MONGO_INITDB_DATABASE: WaosNodeDev
    networks:
      - local

  mongo-express:
    image: mongo-express
    ports:
      - 8081:8081
    environment:
      ME_CONFIG_MONGODB_ADMINUSERNAME: root
      ME_CONFIG_MONGODB_ADMINPASSWORD: root
    networks:
      - local

networks:
  local:
    driver: overlay
